---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medicare-checker-reports-pvc
  namespace: healthcare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports
  namespace: healthcare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard